### ISSUE TITLE
Discussão sobre definição da marca

### ISSUE THREAD

**Issue by kvnol** [cubonetwork/meetup-serverless-sp#1]
rép, people!

O @LFeh trocou uma ideia comigo para pensar numa marca para o Meetup e desenhei algumas opções, vou postando cada opção num comentário, com as versões e tal.

![image](https://user-images.githubusercontent.com/3299130/33130794-a2ff5538-cf7b-11e7-827d-c1b581656d0a.png)

###### PS: Estou do trampo, não tenho as versões aqui, mas chegando em casa atualizo a issue.

**Comment by kvnol** [comment]
Primeira opção.

### White ([ver no Dribbble](https://dribbble.com/shots/3966237-Serverless-SP-Meetup-Logo))
![image](https://user-images.githubusercontent.com/3299130/33130815-b6be34ae-cf7b-11e7-8d84-3ddecd48a7b4.png)

### Black ([ver no Dribbble](https://dribbble.com/shots/3966241-Serverless-SP-Meetup-Logo-black))
![image](https://user-images.githubusercontent.com/3299130/33130820-baf347f8-cf7b-11e7-908c-97cb5f134f6c.png)

### Yellow ([ver no Dribbble](https://dribbble.com/shots/3966245-Serverless-SP-Meetup-Logo-yellow))
![image](https://user-images.githubusercontent.com/3299130/33130844-d02a7df8-cf7b-11e7-8a95-d523bce4e3a2.png)

**Comment by Xhamps** [comment]
Gostei mais da ideia do logo com o símbolo da lambda.
Esse com o raio fica muito vinculado com o logo do framework e não acho legal vincular muito.

@kvnol parabéns, ficou ótimo todos os logos, gostei muito todos.

**Comment by wenderjean** [comment]
@kvnol Ficaram bem legais as opções, eu curti muito a do simbolo da Lambda.

**Comment by CarolPC** [comment]
@kvnol parabéns, ficou muito legal!!! Gostei bastante do Lambda, também!

**Comment by danilodevhub** [comment]
Louco demais @kvnol Parabéns!!! 
Tô com a galera, curti a última opção com símbolo do Lambda em preto

**Comment by LFeh** [comment]
To com o pessoal, esse com o símbolo do Lambda em preto ficou insano!

**Comment by kvnol** [comment]
Maravilha, galera. Acho que está decidido então, chegando em casa faço alguns últimos ajustes de alinhamentos e cores e subo um PR nesse repositório.

**Comment by LFeh** [comment]
Monstro!

**Comment by kvnol** [comment]
PRs abertos! :heart:

**Comment by LFeh** [comment]
Aprovados!
